

author: 
    name: Daniil10295
    url: https://github.com/MGS-Daniil
title: Embed Generator
description: Создай свою ссылку с эмбедом
repository: https://github.com/MGS-Daniil/Embed-Discord
language: ru
