
title: Embed Generator
author-name: Daniil10295
author-url: https://github.com/MGS-Daniil
email: chernyak.daniil.2010@gmail.com
description: Создай свою ссылку с эмбедом
url: https://mgs-daniil.github.io/Embed-Discord/
domain: mgs-daniil.github.io
repository: https://github.com/MGS-Daniil/Embed-Discord
language: ru

plugins:
    - "jekyll-relative-links"
    - "jekyll-metadata"